# Generated by Django 4.2.14 on 2024-10-15 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_doc_appointment_symptoms_and_more'),
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.doc_appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescription', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(default='Pending', max_length=20)),
                ('Appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userapp.doc_appointment')),
            ],
        ),
    ]
